### ISSUE TITLE
Implement a way to provide feedback to user for per frame events

### ISSUE THREAD

**Issue by wkozyra95** [membraneframework/video_compositor#102]
e.g. if we want to display a warning that the frame is missing or to old it would generate to much noise.

Some ideas on how we could approach it:
- Throttling specific log calls (it would require additional abstraction on the logger, it would be annoying to use across different crates.
  - We could avoid the additional abstraction if we just implement very basic throttling based on the string that is printed, but that could have undesired consequences.
- Only log the first time it happens for e.g. input. It's problematic, we would have to keep bunch of local states just for logging, sometimes in places where we didn't expect to have mutabliti
- Implement metrics and log summaries periodically

**Comment by WojciechBarczynski** [comment]
I don't know if this is still valid. With tracing logging level is highly configurable and multiple warn / error logs shouldn't occur in the working setup.
