### ISSUE TITLE
Multiple inputs not working

### ISSUE THREAD

**Issue by noituri** [membraneframework/video_compositor#110]
I tried running compositor with multiple inputs and it freezed on the first frame

**Comment by WojciechBarczynski** [comment]
Hmm, the queue seems to be working fine, but renderer breaks sth

**Comment by wkozyra95** [comment]
Can you provide an example e.g. on a separate branch? I added more than one input using layout transformation and it all rendered correctly

**Comment by noituri** [comment]
I did use neighbouring ports. I wasn't aware that ffmpeg reserves neighbour port as well
