### ISSUE TITLE
Improve shader compilation / validation error messages

### ISSUE THREAD

**Issue by WojciechBarczynski** [membraneframework/video_compositor#324]
Error messages provided to users on shader registration could be better.
I found particularly frustrating: 
1. Providing span of error as string character placement, rather than as line:character placement, like:
```console
Span { start: 624, end: 641 }
```

2. Non-descriptive type mismatch errors, like:
```console
Operation Multiply can't work with [35] and [19]
```
Intead of:
```console
Operation Multiply can't work with "f32" and "u32
```
</br>

We can also consider adding a simple script for parsing/validating shaders, validating shaders from the path, and allowing to check shader correctness without starting the whole VC server.
I mean running sth like:
```console
cargo run -r --bin validate_shader -- --path_to_wgsl_file
```

**Comment by wkozyra95** [comment]
I think we already have to much executable, so I would prefer to avoid adding anything new, but agree with the sentiment about the error messages.

Not related to this issue, but for a while I'm considering creating catch all bin that runs few different checks/tests/validations/generations, so validation of our shaders could be part of that too.
