### ISSUE TITLE
Extract the mp4 parsing logic from the mp4 input and prepare it for accepting fragments of mp4 files

### ISSUE THREAD

**Issue by jerzywilczek** [membraneframework/video_compositor#406]
The libraries we use for parsing mp4 files handle fragmentation in different ways.
- `symphonia` needs to be passed a `MediaSourceStream` with `Seek` disabled. This stream should get fragments appended to the end, and the reader will check the unparsed part when it needs more data automatically, upon calling `next_packet` when it's internal parsed buffer is empty
- `mp4-rs` has a dedicated method for parsing fragments one by one, so when no more samples can be extracted from the current reader, it needs to be fed the next sample manually

Perhaps it was a bad decision to use `symphonia` and maybe we should do the work it allowed us to avoid and stop using it. This should become clear when doing this task.

**Comment by WojciechBarczynski** [comment]
Is't it done?
