### ISSUE TITLE
New mechanism for sending events back to the client

### ISSUE THREAD

**Issue by noituri** [membraneframework/video_compositor#408]
Currently `WaitForNextFrame` query waits until an input frame is ready to be rendered. That means:
- The decoded input frame is already in the buffer 
- The input's offset <  current PTS
- Pipeline processing is already started (`start` request was sent)

The problem is when we want to check whether an input is ready before the pipeline processing has started. The query request will be blocked until the pipeline is started + the above requirements are met.

We potentially want to support these cases:
1.  Next frame is ready to be rendered 
2. Next frame was decoded and is in the buffer

Things to consider in the 2nd case:
- When should we take an input's offset into account? Is a frame ready when it's decoded, or is it ready when it's decoded + `offset < current PTS`

**Comment by WojciechBarczynski** [comment]
WebSockets events should handle this.

Can we close this?
cc @wkozyra95 @noituri

**Comment by wkozyra95** [comment]
> WebSocket events should handle this.

yes

> Can we close this?

No, I still need to write docs
