### ISSUE TITLE
Empty views break layouting behaviour

### ISSUE THREAD

**Issue by WojciechBarczynski** [membraneframework/video_compositor#501]
The input stream is 1600x900 FFmpeg `testsrc`, output is 1920x1080.

```typescript
function sceneWithInputs(n: number): Component {
    const inputStream: Component = {
        type: "input_stream",
        input_id: "input_1",

    };

    const tiles: Array<Component> = Array.from({ length: n }, (_, i) => {
        const text: Component = {
            type: "text",
            text: `InputStream ${i}`,
            font_size: 50,
        };

        return {
            type: "view",
            background_color_rgba: "#007BFFFF",
            overflow: "fit",
            children: [
                inputStream,
                text
            ]
        };
    });

    return {
        type: "tiles",
        id: "tile",
        children: tiles,
        transition: {
            duration_ms: 700,
            easing_function: {
                function_name: "cubic_bezier",
                points: [0.35, 0.22, 0.1, 0.8]
            }
        }
    }
}
```
behaves as expected (example screenshot):
<img width="1512" alt="Screenshot 2024-04-09 at 17 31 38" src="https://github.com/membraneframework/video_compositor/assets/104033489/51814687-ddee-4669-8149-b352338cb9af">

However, once I add empty views:
```typescript
function sceneWithInputs(n: number): Component {
    const inputStream: Component = {
        type: "input_stream",
        input_id: "input_1",
    };

    const tiles: Array<Component> = Array.from({ length: n }, (_, i) => {
        const text: Component = {
            type: "text",
            text: `InputStream ${i}`,
            font_size: 50,
        };

        const emptyView: Component = { type: "view" };
        const centeredText: Component = {
            type: "view",
            children: [emptyView, text, emptyView],
        };

        return {
            type: "view",
            background_color_rgba: "#007BFFFF",
            overflow: "fit",
            children: [
                inputStream,
                centeredText
            ]
        };
    });

    return {
        type: "tiles",
        id: "tile",
        children: tiles,
        transition: {
            duration_ms: 700,
            easing_function: {
                function_name: "cubic_bezier",
                points: [0.35, 0.22, 0.1, 0.8]
            }
        }
    }
}
```
I notice weird behavior:

https://github.com/membraneframework/video_compositor/assets/104033489/02f8f0d8-1441-4031-a496-0b879a8ca05f

I'm not sure, but this seems to be a layout engine bug, but I might interpret sth wrong.

**Comment by wkozyra95** [comment]
It looks correct:
- first view in tile have a fit option so it will fit all the children
- first view have 2 children(input stream + another view)
  - input stream has a well defined size
  - view does not have a size (child does not affect parent size)

So this fit option does not scale anything because second child have dynamic size so it can lower it. When view size becomes zero the only remaining child is scaled down.

**Comment by WojciechBarczynski** [comment]
I find it unintuitive, that text in such a case doesn't specify "another view" size. I know it's hard to implement, but using this API seems to me to be significantly harder. Moreover, I don't know how users could specify such a size if they want to just center text. They can't know that size upfront.

**Comment by wkozyra95** [comment]
I understand that final result is not intuitive, but I would argue that each behavior is perfectly intuitive locally and you just did not expect what will result in composing behvior like that.

>  Moreover, I don't know how users could specify such a size if they want to just center text. They can't know that size upfront.

I just described why this code renders what it does. If your goal was to center the text, then scene itself is incorrect. 

Default behavior for View children is to place them in a row so you are displaying them next to each other. So you are displaying input stream and text next to it. If you want to display them on top of each other then one of them or both  need to be absolutely positioned.

**Comment by WojciechBarczynski** [comment]
Yep, I understand that this won't display text on top of the video without absolute positioning (I mentioned it [here](https://github.com/membraneframework/video_compositor/issues/500#:~:text=center%20aligned%20text.-,Problem,-I%20can%27t%20use)). I just wanted to keep this example as simple as possible and demonstrate that behavior.

I think that requiring providing view width and height to use absolute positioning becomes a headache when view size is unknown at "compile time" (or requires from user to perform some pixel calculations). I think this significantly impacts the overall user experience. Even something as simple as tiling with additional text overlays for each tile (literally plausible WebRTC recording use case :P) requires some hacking with rescalers to achieve the desired effect. If we would allow layout children to set/modify parent resolution, many similar problems might be solvable.

The current solution tries to imitate flex/HTML behavior, but IMO it lacks many important parts, that make it unintuitive for larger scenes. I think that currently calculating "by hand"/"by user" each layout position is faster / more intuitive (obviously centering components with unknown sizes can't be done this way), which doesn't speak in favor of our API.

**Comment by wkozyra95** [comment]
> If we would allow layout children to set/modify parent resolution, many similar problems might be solvable

This is a very handwavy suggestion that **might** solve the problem. What are you actually suggesting? What behavior would you expect? Saying that child should affect parent size is not a behavior, how child should affect the parent and when?

>  I think this significantly impacts the overall user experience. Even something as simple as tiling with additional text overlays for each tile 

This is not an issue with tiling or centering text:
- centering text is relatively easy inside the view (The problem in your case was that view had a size zero)
- The problem is also not caused by tailing because you would have a similar problem when centering text over input stream outside of Tiles component.


How you should do that:
- If you know input stream resolution then set size of the other view to the same value and position it absolutlly
- If you don't know resolution then:
  - wrap input stream in rescaler and pick some resolution that has the same aspect ratio as tile 
  - set the same resolution on the first view
  
How could improve overlays like that:
- Add separate component overlay that is matching other component size and renders on top
- Support for using `left` and `right` fields at the same time

Both of those seems to be reasonable features to add.

**Comment by wkozyra95** [comment]
Ok I admit there is a problem with centering itself (even if parent size is well-known). I hit that when trying to generate some example input stream that can be used in docs. I'm not sure what is the best solution for that yet, but I'll think about it more.

**Comment by wkozyra95** [comment]
We might consider adding `align-items` option, this way you could write centered text like this
```typescript
{
  type: "view",
  align_items: "center",
  children: [
    { type: "view" },
    text_composnent
    { type: "view" },
  ]
}
```

or if we also add justify-content
```typescript
{
  type: "view",
  align_items: "center",
  justify_content: "center"
  children: [
    text_composnent
  ]
}
```

(I did not use css for a while so I might have mixed those 2 options together, but the general idea should still be clear)
